rc ci finalization

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,105 +1,4 @@
-# specialized version of the release-tag.sh pipeline script
-# we habe to commit tag versions to galaxy.yml and to our cloud-ee.yml files
-release_tag:
-  stage: build
-  image: docker.io/tobiashvmz/pve-cloud-ci:202601081028
-  script:
-    - git config --global user.name "$GITLAB_USER_NAME"
-    - git config --global user.email "$GITLAB_USER_EMAIL"
-
-    - new_tag=$(/scripts/get-new-tag.sh)
-
-    # update galaxy yaml
-    - |
-      sed -i "s/^version:\s.*$/version: $new_tag/" galaxy.yml
-    - git add galaxy.yml
-    # update cloud ee defintion file
-    - |
-      sed -i "s/version:.*sed/version: $new_tag # sed/" cloud-ee.yaml
-    - git add cloud-ee.yaml
-
-    - git commit -m "Update collection version to $new_tag / update schemas."
-    - git push origin HEAD:master
-
-    # cleanup delete rc tags
-    - |
-      if git ls-remote --heads origin | grep -q "refs/heads/${new_tag}-rc"; then
-        echo "deleting rc release branch ${new_tag}-rc"
-        git push origin --delete "${new_tag}-rc"
-      else
-        echo "no rc branch found! prod release without rc first?"
-      fi
-
-    # tag and push
-    - git tag "$new_tag" -m "$CI_COMMIT_TAG"
-    - git push origin "$new_tag"
-
-    # trigger pipelines
-    - sleep 10 # small buffer for gitlab ci
-    - |
-      curl --request POST \
-        --form "token=${CI_JOB_TOKEN}" \
-        --form "ref=${new_tag}" \
-        "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/trigger/pipeline"
-  rules:
-    - if: '$CI_COMMIT_TAG =~ /^release-[a-z]+$/'
-  resource_group: deploy-prod
-
-
-# specialized version of the rc-tag.sh pipeline script
-# we have to write our rc version to galaxy.yml. we dont build the execution environment
-# for release candidates
-rc_tag:
-  stage: build
-  image: docker.io/tobiashvmz/pve-cloud-ci:202601081028
-  script:
-    - git config --global user.name "$GITLAB_USER_NAME"
-    - git config --global user.email "$GITLAB_USER_EMAIL"
-
-    - new_tag=$(/scripts/get-new-tag.sh)
-    - /scripts/rc-branch.sh $new_tag
-
-    - |
-      # create new rc release tag and propagate
-      rc_tags=$(git tag -l | grep -E "^$new_tag-rc[0-9]+$" || true)
-
-      if [ -z "$rc_tags" ]; then
-        rc_vers_tag="$new_tag-rc0"
-      else
-        latest_rc=$(echo "$rc_tags" | sort -V | tail -n 1)
-        rc_num=${latest_rc##*-rc}   # removes everything up to last "-rc"
-        
-        next_rc=$((rc_num + 1))
-        
-        rc_vers_tag="$new_tag-rc${next_rc}"
-      fi
-
-      echo $rc_vers_tag
-
-    # update galaxy yaml
-    - |
-      sed -i "s/^version:\s.*$/version: $rc_vers_tag/" galaxy.yml
-    - git add galaxy.yml
-
-    - git commit -m "Set collection rc version to $rc_vers_tag / update schemas."
-    - git push origin HEAD:$new_tag-rc
-
-    # tag and push
-    - git tag "${rc_vers_tag}" -m "$CI_COMMIT_TAG" # again save the initial rc tag for propagation
-    - git push origin "${rc_vers_tag}"
-
-    # trigger pipelines
-    - sleep 10 # small buffer for gitlab ci
-    - |
-      curl --request POST \
-        --form "token=${CI_JOB_TOKEN}" \
-        --form "ref=${rc_vers_tag}" \
-        "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/trigger/pipeline"
-  rules:
-    - if: '$CI_COMMIT_TAG =~ /^rc-[a-z]+$/'
-  resource_group: deploy-prod
-
-
+# schemas doesnt have an rc build as its very simple
 pve_cloud_schemas_upstream:
   stage: build
   image: docker.io/tobiashvmz/pve-cloud-ci:202601081028
@@ -110,7 +9,6 @@ pve_cloud_schemas_upstream:
     - /scripts/upstream-push.sh "Update pve-cloud-schemas version to $PVE_CLOUD_SCHEMAS"
   rules:
     - if: ( $PVE_CLOUD_SCHEMAS != null || $PVE_CLOUD_SCHEMAS =~ /^./ ) # set by upstream
-
 
 # pipeline trigger if the upstream releases
 py_pve_cloud_upstream:
@@ -123,6 +21,20 @@ py_pve_cloud_upstream:
   rules:
     - if: '$PY_PVE_CLOUD != null && $PY_PVE_CLOUD != "" && $UPSTREAM_TAG_MESSAGE =~ /^release-.*/' # set by upstream
 
+py_pve_cloud_rc_upstream:
+  stage: build
+  image: docker.io/tobiashvmz/pve-cloud-ci:202601081028
+  script:
+    # get the latest prod tag
+    - new_tag=$(/scripts/get-new-tag.sh)
+    - echo $new_tag
+    # switch to rc branch
+    - /scripts/rc-branch.sh $new_tag
+    # set rc version for py-pve-cloud-dependency
+    - sed -i "s/^py-pve-cloud==.*$/py-pve-cloud==${PY_PVE_CLOUD//-/}/" meta/ee-requirements.txt
+    - /scripts/upstream-push.sh "Set py-pve-cloud rc version to ${PY_PVE_CLOUD//-/}" "${new_tag}-rc"
+  rules:
+    - if: '$PY_PVE_CLOUD != null && $PY_PVE_CLOUD != "" && $UPSTREAM_TAG_MESSAGE =~ /^rc-.*/' # set by upstream, trigger for rc release
 
 pve_cloud_backup_upstream:
   stage: build
@@ -151,6 +63,105 @@ pve_cloud_backup_rc_upstream:
   rules:
     - if: '$PVE_CLOUD_BACKUP != null && $PVE_CLOUD_BACKUP != "" && $UPSTREAM_TAG_MESSAGE =~ /^rc-.*/' # set by upstream
 
+# specialized version of the release-tag.sh pipeline script
+# we habe to commit tag versions to galaxy.yml and to our cloud-ee.yml files
+release_tag:
+  stage: build
+  image: docker.io/tobiashvmz/pve-cloud-ci:202601081028
+  script:
+    - git config --global user.name "$GITLAB_USER_NAME"
+    - git config --global user.email "$GITLAB_USER_EMAIL"
+
+    - new_tag=$(/scripts/get-new-tag.sh)
+
+    # update galaxy yaml
+    - |
+      sed -i "s/^version:\s.*$/version: $new_tag/" galaxy.yml
+    - git add galaxy.yml
+
+    # update cloud ee defintion file
+    - |
+      sed -i "s/version:.*sed/version: $new_tag # sed/" cloud-ee.yaml
+    - git add cloud-ee.yaml
+
+    - git commit -m "Update collection version to $new_tag / update schemas."
+    - git push origin HEAD:master
+
+    # cleanup delete rc tags - on prod release we cleanup rc branch
+    - |
+      if git ls-remote --heads origin | grep -q "refs/heads/${new_tag}-rc"; then
+        echo "deleting rc release branch ${new_tag}-rc"
+        git push origin --delete "${new_tag}-rc"
+      else
+        echo "no rc branch found! prod release without rc first?"
+      fi
+
+    # release tag and push
+    - git tag "$new_tag" -m "$CI_COMMIT_TAG"
+    - git push origin "$new_tag"
+
+    # trigger pipelines
+    - sleep 10 # small buffer for gitlab ci
+    - |
+      curl --request POST \
+        --form "token=${CI_JOB_TOKEN}" \
+        --form "ref=${new_tag}" \
+        "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/trigger/pipeline"
+  rules:
+    - if: '$CI_COMMIT_TAG =~ /^release-[a-z]+$/'
+  resource_group: deploy-prod
+
+# specialized version of the rc-tag.sh pipeline script
+# we have to write our rc version to galaxy.yml. we dont build the execution environment
+# for release candidates
+rc_tag:
+  stage: build
+  image: docker.io/tobiashvmz/pve-cloud-ci:202601081028
+  script:
+    - git config --global user.name "$GITLAB_USER_NAME"
+    - git config --global user.email "$GITLAB_USER_EMAIL"
+
+    - new_tag=$(/scripts/get-new-tag.sh)
+    - /scripts/rc-branch.sh $new_tag # switch to rc branch
+
+    # determine the rc release tag
+    - |
+      rc_tags=$(git tag -l | grep -E "^$new_tag-rc[0-9]+$" || true)
+
+      if [ -z "$rc_tags" ]; then
+        rc_vers_tag="$new_tag-rc0"
+      else
+        latest_rc=$(echo "$rc_tags" | sort -V | tail -n 1)
+        rc_num=${latest_rc##*-rc}   # removes everything up to last "-rc"
+        
+        next_rc=$((rc_num + 1))
+        
+        rc_vers_tag="$new_tag-rc${next_rc}"
+      fi
+
+      echo $rc_vers_tag
+
+    # update galaxy yaml - no need to update cloud-ee.yml we dont build it in release candidates
+    - |
+      sed -i "s/^version:\s.*$/version: $rc_vers_tag/" galaxy.yml
+    - git add galaxy.yml
+
+    # commit and tag rc
+    - git commit -m "Set collection rc version to $rc_vers_tag / update schemas."
+    - git push origin HEAD:$new_tag-rc
+    - git tag "${rc_vers_tag}" -m "$CI_COMMIT_TAG" # again save the initial rc tag for propagation
+    - git push origin "${rc_vers_tag}"
+
+    # trigger pipelines
+    - sleep 10 # small buffer for gitlab ci
+    - |
+      curl --request POST \
+        --form "token=${CI_JOB_TOKEN}" \
+        --form "ref=${rc_vers_tag}" \
+        "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/trigger/pipeline"
+  rules:
+    - if: '$CI_COMMIT_TAG =~ /^rc-[a-z]+$/'
+  resource_group: deploy-prod
 
 release_galaxy:
   stage: deploy
@@ -181,7 +192,6 @@ release_ee:
   timeout: 2h
   resource_group: deploy-prod-ee # don't run this twice ;)
 
-
 release_docs:
   stage: deploy
   image: tobiashvmz/pve-cloud-pyci:2026010412
@@ -204,7 +214,6 @@ release_docs:
     - mkdocs gh-deploy # update github pages branch - always, might have doc changes but no schema
   rules:
     - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'
-
 
 format_source:
   stage: build
